### ISSUE TITLE
inconsistent output as the input grows

### ISSUE THREAD

**Issue by normanzb** [devbanana/crockford-base32#2]
if we look at base64, which store 6 bits per input byte in each output char, it would generate a consistent result that:
as we add more bytes to the same input data, and each time we encode it with base64, the beginning bits that is multiple of 6 should always generate the same result.

e.g. when you feed it 1 byte 0x74, you get `dA`:

`btoa('\x74') == 'dA=='`

this is because 0x74 in binary form is 01110100, the beginning 6 bits 011101 is 29 which is the character `d` according to https://base64.guru/learn/base64-characters.

add one more 0x74, you get `dHQ`.

add one more 0x75, it gives you `dHR1`

you see the beginning of the result will always be the same as long as it is generated from input data that is multiple of 6.

but this package works differently:

for `[0x74]`, it generates `3M`;  `CrockfordBase32.encode('\x74')`
for `[0x74, 0x74]`, it generates `0X3M`,
for `[0x74, 0x74, 0x75]`, it generates `78X3N`.

the reason of this inconsistency is due to the lib is reading the bits from the end, i dont think that is intended and compliant to the spec? since crockford base32 only differs in character table?

**Comment by normanzb** [comment]
according to https://cryptii.com/pipes/crockford-base32

0x74 should generate EG

![image](https://github.com/devbanana/crockford-base32/assets/130634/1b6bbdd3-1420-41c4-8ae6-e1b1c1e21963)

**Comment by devbanana** [comment]
Hi @normanzb. Thanks for the report. I don’t remember why I made the decision to read from right to left when I created this package, but I realize you are correct and input should be read from left to right.

I created PR #3 to try to fix this. Let me know if that seems to resolve the issue for you.

**Comment by normanzb** [comment]
hi @devbanana, the MR LGTM. great job man, really appreciate it :shipit:
